const HomePage = () => {

    return (

        <>

            <h2>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Officiis sapiente corporis, quam aperiam pariatur iure minima, ratione fuga eveniet laudantium rerum velit labore ea dolore. Sunt cum adipisci ut libero? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellat et, asperiores illo ipsa ullam deserunt ab, distinctio nostrum quisquam beatae ipsam neque unde explicabo ducimus iure. Non aperiam temporibus iure!  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Placeat nam facilis unde odit aut quibusdam nemo eos. Temporibus eum optio non ex! Repellat harum accusantium et quia sed magnam recusandae.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Officiis sapiente corporis, quam aperiam pariatur iure minima, ratione fuga eveniet laudantium rerum velit labore ea dolore. Sunt cum adipisci ut libero? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellat et, asperiores illo ipsa ullam deserunt ab, distinctio nostrum quisquam beatae ipsam neque unde explicabo ducimus iure. Non aperiam temporibus iure!  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Placeat nam facilis unde odit aut quibusdam nemo eos. Temporibus eum optio non ex! Repellat harum accusantium et quia sed magnam recusandae.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Officiis sapiente corporis, quam aperiam pariatur iure minima, ratione fuga eveniet laudantium rerum velit labore ea dolore. Sunt cum adipisci ut libero? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellat et, asperiores illo ipsa ullam deserunt ab, distinctio nostrum quisquam beatae ipsam neque unde explicabo ducimus iure. Non aperiam temporibus iure!  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Placeat nam facilis unde odit aut quibusdam nemo eos. Temporibus eum optio non ex! Repellat harum accusantium et quia sed magnam recusandae.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Officiis sapiente corporis, quam aperiam pariatur iure minima, ratione fuga eveniet laudantium rerum velit labore ea dolore. Sunt cum adipisci ut libero? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellat et, asperiores illo ipsa ullam deserunt ab, distinctio nostrum quisquam beatae ipsam neque unde explicabo ducimus iure. Non aperiam temporibus iure!  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Placeat nam facilis unde odit aut quibusdam nemo eos. Temporibus eum optio non ex! Repellat harum accusantium et quia sed magnam recusandae.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Officiis sapiente corporis, quam aperiam pariatur iure minima, ratione fuga eveniet laudantium rerum velit labore ea dolore. Sunt cum adipisci ut libero? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellat et, asperiores illo ipsa ullam deserunt ab, distinctio nostrum quisquam beatae ipsam neque unde explicabo ducimus iure. Non aperiam temporibus iure!  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Placeat nam facilis unde odit aut quibusdam nemo eos. Temporibus eum optio non ex! Repellat harum accusantium et quia sed magnam recusandae.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Officiis sapiente corporis, quam aperiam pariatur iure minima, ratione fuga eveniet laudantium rerum velit labore ea dolore. Sunt cum adipisci ut libero? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellat et, asperiores illo ipsa ullam deserunt ab, distinctio nostrum quisquam beatae ipsam neque unde explicabo ducimus iure. Non aperiam temporibus iure!  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Placeat nam facilis unde odit aut quibusdam nemo eos. Temporibus eum optio non ex! Repellat harum accusantium et quia sed magnam recusandae.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Officiis sapiente corporis, quam aperiam pariatur iure minima, ratione fuga eveniet laudantium rerum velit labore ea dolore. Sunt cum adipisci ut libero? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellat et, asperiores illo ipsa ullam deserunt ab, distinctio nostrum quisquam beatae ipsam neque unde explicabo ducimus iure. Non aperiam temporibus iure!  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Placeat nam facilis unde odit aut quibusdam nemo eos. Temporibus eum optio non ex! Repellat harum accusantium et quia sed magnam recusandae.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Officiis sapiente corporis, quam aperiam pariatur iure minima, ratione fuga eveniet laudantium rerum velit labore ea dolore. Sunt cum adipisci ut libero? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellat et, asperiores illo ipsa ullam deserunt ab, distinctio nostrum quisquam beatae ipsam neque unde explicabo ducimus iure. Non aperiam temporibus iure!  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Placeat nam facilis unde odit aut quibusdam nemo eos. Temporibus eum optio non ex! Repellat harum accusantium et quia sed magnam recusandae.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Officiis sapiente corporis, quam aperiam pariatur iure minima, ratione fuga eveniet laudantium rerum velit labore ea dolore. Sunt cum adipisci ut libero? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellat et, asperiores illo ipsa ullam deserunt ab, distinctio nostrum quisquam beatae ipsam neque unde explicabo ducimus iure. Non aperiam temporibus iure!  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Placeat nam facilis unde odit aut quibusdam nemo eos. Temporibus eum optio non ex! Repellat harum accusantium et quia sed magnam recusandae.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Officiis sapiente corporis, quam aperiam pariatur iure minima, ratione fuga eveniet laudantium rerum velit labore ea dolore. Sunt cum adipisci ut libero? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellat et, asperiores illo ipsa ullam deserunt ab, distinctio nostrum quisquam beatae ipsam neque unde explicabo ducimus iure. Non aperiam temporibus iure!  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Placeat nam facilis unde odit aut quibusdam nemo eos. Temporibus eum optio non ex! Repellat harum accusantium et quia sed magnam recusandae.

            </h2>

        </>
    )
}

export default HomePage